INSERT INTO genres (name) VALUES
                              ('Fiction'),
                              ('Non-Fiction'),
                              ('Mystery'),
                              ('Thriller'),
                              ('Science Fiction'),
                              ('Fantasy'),
                              ('Romance'),
                              ('Historical Fiction'),
                              ('Horror'),
                              ('Biography'),
                              ('Autobiography'),
                              ('Memoir'),
                              ('Self-Help'),
                              ('Philosophy'),
                              ('Travel'),
                              ('Science'),
                              ('Poetry'),
                              ('Drama'),
                              ('Comedy'),
                              ('Satire'),
                              ('Adventure'),
                              ('Children\'s Literature'),
                              ('Young Adult'),
                              ('Graphic Novels'),
                              ('Crime'),
                              ('Paranormal'),
                              ('Dystopian'),
                              ('Humor'),
                              ('Business');